In [ ]:
"All the chai-1 outputs for scoring metrics will be generated into a .csv file"

In [ ]:
import os
import glob
import numpy as np
import pandas as pd
import csv

In [2]:
base_directory = "/Users/JB/Rotation_bkslab/250130_chaifold" # Change this to a directory with all Chai-1 outputs
output_file = "/Users/JB/Rotation_bkslab/250130_chaifold/chai_scores_idx_0.xlsx" #Make an excel file where all the results will be saved.

out_folders = [folder for folder in glob.glob(os.path.join(base_directory, "*.out")) if os.path.isdir(folder)]

data_list = []

for out_folder in out_folders:
    npz_file_path = os.path.join(out_folder, "scores.model_idx_0.npz")
    data = np.load(npz_file_path)

    aggregate_score = data.get('aggregate_score', np.nan)
    iptm = data.get('iptm', np.nan)
    ptm = data.get('ptm', np.nan)
    per_chain_ptm = data.get('per_chain_ptm', np.nan)
    per_chain_pair_iptm = data.get('per_chain_pair_iptm', np.nan)
    has_inter_chain_clashes = data.get('has_inter_chain_clashes', np.nan)
    chain_chain_clashes = data.get('chain_chain_clashes', np.nan)

    data_list.append({
        "Index": os.path.basename(out_folder),
        "Aggregate Score": aggregate_score,
        "iPTM": iptm,
        "pTM": ptm,
        "pTM per chain": per_chain_ptm,
        "iPTM per chain pair": per_chain_pair_iptm,
        "Interchain clash?": has_inter_chain_clashes,
        "Matrix chain-chain clashes": chain_chain_clashes
    })

Chai_output_scores = pd.DataFrame(data_list)
Chai_output_scores.to_excel(output_file, index=False)

In [6]:
#Designate a file path to one of .npz file and check what are the output contents available for each dataset.
file_path = "/Users/JB/Rotation_bkslab/250115_chaifold/Chai_output/mac-x2820.out/scores.model_idx_0.npz"
data = np.load(file_path)

print("Keys in the NPZ file:", data.files)

for key in data.files:
    print(f"\n--- {key} ---")
    print(data[key])

Keys in the NPZ file: ['aggregate_score', 'ptm', 'iptm', 'per_chain_ptm', 'per_chain_pair_iptm', 'has_inter_chain_clashes', 'chain_chain_clashes']

--- aggregate_score ---
[0.8695203]

--- ptm ---
[0.95707834]

--- iptm ---
[0.8476308]

--- per_chain_ptm ---
[[0.95399    0.63493437]]

--- per_chain_pair_iptm ---
[[[0.95399    0.44597793]
  [0.8476308  0.63493437]]]

--- has_inter_chain_clashes ---
[False]

--- chain_chain_clashes ---
[[[0 0]
  [0 0]]]
